//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3kiursWPF1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public int Id_Collection { get; set; }
        public int Id_Vystavka { get; set; }
        public int Id_Kaktus { get; set; }
    
        public virtual Kaktus Kaktus { get; set; }
        public virtual Vystavka Vystavka { get; set; }
    }
}
