//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3kiursWPF1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        public int Id_Login { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Id_User { get; set; }
        public string Role { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
